import { InfrastructureError } from '../../shared/errors/AppError.js';

/**
 * Where temperature readings come from.
 *
 * The honesty problem
 * -------------------
 * The requirement is explicit that readings must not be fabricated, and this
 * project has no physical reefer attached to it. Those two facts are only
 * compatible if invented data is *labelled as invented*, everywhere it surfaces
 * and permanently.
 *
 * So every reading this gateway produces carries a `source` in its event
 * payload, and that field is part of the immutable record:
 *
 *   SIMULATED - generated by the model below. Shown as "Simulated" in the
 *               chart legend, the timeline and the PDF, forever. It is not
 *               presented as sensor data, because it is not sensor data.
 *   EXTERNAL  - fetched from a real feed configured via SENSOR_FEED_URL.
 *   MANUAL    - entered by an operator through the API (the pre-existing path,
 *               still available, still audited).
 *
 * With `SENSOR_SOURCE=none` the monitor runs and records nothing, reporting
 * that no feed is configured. That is the correct default for a deployment with
 * no sensors: silence rather than fiction.
 */

export const SENSOR_SOURCES = Object.freeze({
  SIMULATED: 'SIMULATED',
  EXTERNAL: 'EXTERNAL',
  MANUAL: 'MANUAL',
  NONE: 'none',
});

/**
 * A deterministic reefer model.
 *
 * Deterministic on purpose. Seeding from the shipment id and the reading's own
 * timestamp means replaying the same hour for the same shipment produces the
 * same number, so a demonstration is reproducible and a test can assert on it
 * without pinning a random seed globally.
 *
 * The shape is a slow sinusoidal drift inside the declared band plus a small
 * perturbation, with occasional excursions - a reefer whose door has been open
 * or whose compressor has stumbled. It is a plausible *shape*, not a claim
 * about any real container, which is exactly why it is labelled.
 */
export class SimulatedSensorProvider {
  #excursionChance;

  constructor({ excursionChance = 0.08 } = {}) {
    this.#excursionChance = excursionChance;
  }

  get source() {
    return SENSOR_SOURCES.SIMULATED;
  }

  get describes() {
    return 'Deterministic simulation. Not measured data.';
  }

  /** Small, stable hash so the same inputs always give the same output. */
  #noise(seed) {
    let hash = 2166136261;
    for (let index = 0; index < seed.length; index += 1) {
      hash ^= seed.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    // Map to [0, 1).
    return ((hash >>> 0) % 100000) / 100000;
  }

  async read({ aggregateId, at, minTemperatureC, maxTemperatureC, sensorId }) {
    // With no declared range there is no meaningful band to sit inside, so the
    // model centres on a conventional chilled setpoint.
    const min = Number.isFinite(minTemperatureC) ? minTemperatureC : 2;
    const max = Number.isFinite(maxTemperatureC) ? maxTemperatureC : 8;
    const centre = (min + max) / 2;
    const halfBand = Math.max((max - min) / 2, 0.5);

    const epoch = Date.parse(at);
    const hours = epoch / 3_600_000;
    const drift = Math.sin(hours / 7) * halfBand * 0.55;

    const roll = this.#noise(`${aggregateId}|${at}`);
    const jitter = (this.#noise(`${aggregateId}|${at}|j`) - 0.5) * halfBand * 0.4;

    let temperatureC = centre + drift + jitter;

    // An occasional excursion, so the breach path and the alert timeline are
    // actually exercised rather than being theoretically reachable.
    if (roll < this.#excursionChance) {
      const above = this.#noise(`${aggregateId}|${at}|d`) > 0.4;
      const overshoot = halfBand * (1.4 + roll * 6);
      temperatureC = above ? max + overshoot : min - overshoot;
    }

    return {
      temperatureC: Number(temperatureC.toFixed(2)),
      recordedAt: at,
      sensorId: sensorId ?? 'SIM-REEFER-01',
      source: SENSOR_SOURCES.SIMULATED,
    };
  }
}

/**
 * Reads from a real feed.
 *
 * Expects `GET {feedUrl}?containerId=...&at=...` returning
 * `{ temperatureC, recordedAt?, sensorId? }`. A feed that answers with anything
 * else is treated as a fault and produces no reading at all - recording a
 * malformed response as though it were a measurement would put a fiction into
 * an immutable store, which is the one outcome worth failing loudly to avoid.
 */
export class ExternalSensorProvider {
  #feedUrl;
  #timeoutMs;
  #logger;

  constructor({ feedUrl, timeoutMs = 5000, logger }) {
    if (!feedUrl) throw new InfrastructureError('SENSOR_FEED_URL must be set when SENSOR_SOURCE=external.');
    this.#feedUrl = feedUrl;
    this.#timeoutMs = timeoutMs;
    this.#logger = logger;
  }

  get source() {
    return SENSOR_SOURCES.EXTERNAL;
  }

  get describes() {
    return `External sensor feed at ${this.#feedUrl}`;
  }

  async read({ aggregateId, containerCode, at }) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.#timeoutMs);

    try {
      const url = new URL(this.#feedUrl);
      url.searchParams.set('shipmentId', aggregateId);
      if (containerCode) url.searchParams.set('containerId', containerCode);
      url.searchParams.set('at', at);

      const response = await fetch(url, { signal: controller.signal });
      if (!response.ok) {
        this.#logger?.warn('Sensor feed returned a non-OK status; no reading recorded.', {
          aggregateId,
          status: response.status,
        });
        return null;
      }

      const body = await response.json();
      const temperatureC = Number(body?.temperatureC);
      if (!Number.isFinite(temperatureC)) {
        this.#logger?.warn('Sensor feed returned no usable temperature; no reading recorded.', {
          aggregateId,
        });
        return null;
      }

      return {
        temperatureC,
        recordedAt: body.recordedAt ?? at,
        sensorId: body.sensorId ?? null,
        source: SENSOR_SOURCES.EXTERNAL,
      };
    } catch (error) {
      this.#logger?.warn('Could not reach the sensor feed; no reading recorded.', {
        aggregateId,
        reason: error.message,
      });
      return null;
    } finally {
      clearTimeout(timer);
    }
  }
}

/** Records nothing. The default, and the honest answer when no feed exists. */
export class NullSensorProvider {
  get source() {
    return SENSOR_SOURCES.NONE;
  }

  get describes() {
    return 'No sensor feed is configured. No readings are recorded automatically.';
  }

  async read() {
    return null;
  }
}

export function createSensorProvider({ config, logger }) {
  switch (config.sensors.source) {
    case 'simulated':
      return new SimulatedSensorProvider({ excursionChance: config.sensors.excursionChance });
    case 'external':
      return new ExternalSensorProvider({
        feedUrl: config.sensors.feedUrl,
        timeoutMs: config.sensors.timeoutMs,
        logger,
      });
    default:
      return new NullSensorProvider();
  }
}
